# Generated by Django 2.2.2 on 2019-06-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdouban',
            name='field_id',
            field=models.AutoField(db_column='_id', primary_key=True, serialize=False),
        ),
    ]
