# Generated by Django 2.2.2 on 2019-06-16 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='updated',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 6, 16, 7, 56, 33, 260992, tzinfo=utc)),
        ),
    ]
